### ISSUE TITLE
RGB Lights

### ISSUE THREAD

**Issue by dmonty2** [treussart/domoticz_skill#20]
I'd like to add the ability to voice control RGB LED lights.  RGB hex value, dimmer level and scenes.  I can work on the code.  Here is the general idea.

"Set RGB lights in living room to red"
"Set LED lights in living room to blue"

"Dim LED lights in living room to 30 percent"
"Dim LED lights in living room"
"Brighten LED lights in living room"

"Set the scene in living room to romantic"
"Set the scene in living room to relaxing"

API page:
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s

example API URLs:

/json.htm?type=command&param=setcolbrightnessvalue&idx=99&hex=RRGGBB&brightness=100&iswhite=false

/json.htm?type=command&param=switchlight&idx=99&switchcmd=Set%20Level&level=6

/json.htm?type=command&param=switchscene&idx=&switchcmd=

Below is vocab and settings for colors based on FastLED color names & values.

= FastLED color names =
Alice Blue=F0F8FF
Amethyst=9966CC
Antique White=FAEBD7
Aqua=00FFFF
Aquamarine=7FFFD4
Azure=F0FFFF
Beige=F5F5DC
Bisque=FFE4C4
Black=000000
Black Light Fluorescent=A700FF
Blanched Almond=FFEBCD
Blue=0000FF
Blue Violet=8A2BE2
Brown=A52A2A
Burly Wood=DEB887
Cadet Blue=5F9EA0
Candle=FF9329
Carbon Arc=FFFAF4
Chartreuse=7FFF00
Chocolate=D2691E
Clear Blue Sky=409CFF
Cool White Fluorescent=D4EBFF
Coral=FF7F50
Cornflower Blue=6495ED
Cornsilk=FFF8DC
Crimson=DC143C
Cyan=00FFFF
Dark Blue=00008B
Dark Cyan=008B8B
Dark Goldenrod=B8860B
Dark Gray=A9A9A9
Dark Green=006400
Dark Grey=A9A9A9
Dark Khaki=BDB76B
Dark Magenta=8B008B
Dark Olive Green=556B2F
Dark Orange=FF8C00
Dark Orchid=9932CC
Dark Red=8B0000
Dark Salmon=E9967A
Dark Sea Green=8FBC8F
Dark Slate Blue=483D8B
Dark Slate Gray=2F4F4F
Dark Slate Grey=2F4F4F
Dark Turquoise=00CED1
Dark Violet=9400D3
Deep Pink=FF1493
Deep Sky Blue=00BFFF
Dim Gray=696969
Dim Grey=696969
Direct Sunlight=FFFFFF
Dodger Blue=1E90FF
Fairy Light NCC=FF9D2A
Fire Brick=B22222
Floral White=FFFAF0
Forest Green=228B22
Fuchsia=FF00FF
Full Spectrum Fluorescent=FFF4F2
Gainsboro=DCDCDC
Ghost White=F8F8FF
Gold=FFD700
Goldenrod=DAA520
Gray=808080
Green=008000
Green Yellow=ADFF2F
Grey=808080
Grow Light Fluorescent=FFEFF7
Halogen=FFF1E0
High Noon Sun=FFFFFB
High Pressure Sodium=FFB74C
Honeydew=F0FFF0
Hot Pink=FF69B4
Indian Red=CD5C5C
Indigo=4B0082
Ivory=FFFFF0
Khaki=F0E68C
Lavender=E6E6FA
Lavender Blush=FFF0F5
Lawn Green=7CFC00
Lemon Chiffon=FFFACD
Light Blue=ADD8E6
Light Coral=F08080
Light Cyan=E0FFFF
Light Goldenrod Yellow=FAFAD2
Light Green=90EE90
Light Grey=D3D3D3
Light Pink=FFB6C1
Light Salmon=FFA07A
Light Sea Green=20B2AA
Light Sky Blue=87CEFA
Light Slate Gray=778899
Light Slate Grey=778899
Light Steel Blue=B0C4DE
Light Yellow=FFFFE0
Lime=00FF00
Lime Green=32CD32
Linen=FAF0E6
Magenta=FF00FF
Maroon=800000
Medium Aquamarine=66CDAA
Medium Blue=0000CD
Medium Orchid=BA55D3
Medium Purple=9370DB
Medium Sea Green=3CB371
Medium Slate Blue=7B68EE
Medium Spring Green=00FA9A
Medium Turquoise=48D1CC
Medium Violet Red=C71585
Mercury Vapor=D8F7FF
Metal Halide=F2FCFF
Midnight Blue=191970
Mint Cream=F5FFFA
Misty Rose=FFE4E1
Moccasin=FFE4B5
Navajo White=FFDEAD
Navy=000080
Old Lace=FDF5E6
Olive=808000
Olive Drab=6B8E23
Orange=FFA500
Orange Red=FF4500
Orchid=DA70D6
Overcast Sky=C9E2FF
Pale Goldenrod=EEE8AA
Pale Green=98FB98
Pale Turquoise=AFEEEE
Pale Violet Red=DB7093
Papaya Whip=FFEFD5
Peach Puff=FFDAB9
Peru=CD853F
Pink=FFC0CB
Plaid=CC5533
Plum=DDA0DD
Powder Blue=B0E0E6
Purple=800080
Red=FF0000
Rosy Brown=BC8F8F
Royal Blue=4169E1
Saddle Brown=8B4513
Salmon=FA8072
Sandy Brown=F4A460
Sea Green=2E8B57
Seashell=FFF5EE
Sienna=A0522D
Silver=C0C0C0
Sky Blue=87CEEB
Slate Blue=6A5ACD
Slate Gray=708090
Slate Grey=708090
Snow=FFFAFA
Sodium Vapor=FFD1B2
Spring Green=00FF7F
Standard Fluorescent=F4FFFA
Steel Blue=4682B4
Tan=D2B48C
Teal=008080
Thistle=D8BFD8
Tomato=FF6347
Tungsten 100 watt=FFD6AA
Tungsten 40 watt=FFC58F
Turquoise=40E0D0
Violet=EE82EE
Warm Fluorescent=FFF4E5
Wheat=F5DEB3
White=FFFFFF
White Smoke=F5F5F5
Yellow=FFFF00
Yellow Green=9ACD32

**Comment by treussart** [comment]
Hi,

Yes you can !!

If it works I would merge your code.

Best regards
Matthieu
