### ISSUE TITLE
Skill doesn't start

### ISSUE THREAD

**Issue by Raeymeister** [treussart/domoticz_skill#21]
Hi, Thanks for your work on this skill! I tried to install it today on my raspbian installation of MyCroft (NOT picroft).

I followed below steps:

cd /opt/mycroft/skills
sudo git clone https://github.com/treussart/domoticz_skill

Then I altered the conf.cfg file in /opt/mycroft/skills/domoticz_skill
to add right IP of domoticz server and added a light point

When restarting mycroft, I get following error:

21:51:20.547 - mycroft.skills.core:load_skill:106 - INFO - ATTEMPTING TO LOAD SKILL: domoticz_skill with ID domoticz_skill
21:51:20.564 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: domoticz_skill
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 116, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 172, in load_source
module = _load(spec)
File "", line 693, in _load
File "", line 673, in _load_unlocked
File "", line 673, in exec_module
File "", line 222, in _call_with_frames_removed
File "/opt/mycroft/skills/domoticz_skill/init.py", line 27, in 
Domoticz = import('Domoticz').Domoticz
File "/opt/mycroft/skills/domoticz_skill/Domoticz.py", line 3, in 
import ConfigParser
ImportError: No module named 'ConfigParser'

Many thanks in advance for your assistance.

**Comment by treussart** [comment]
Hi
Because It's for Python2, ConfigParser renamed into -> configparser
I can edit to match with Python3 if you want.
https://docs.python.org/3/library/configparser.html

**Comment by Raeymeister** [comment]
Hi, THANKS, 

What I did: in Domoticz.py, I changed "import ConfigParser" to "import configparser"

Now, it starts up, tomorrow I continue playing with your solution.

Many thanks for your swift response!

**Comment by Raeymeister** [comment]
Ok, I needed to alter 2 extra things to make it work with python 3:

in        /opt/mycroft/skills/domoticz_skill 
do       sudo nano Domoticz.py 

add: (with the other imports)

import urllib.request


Change:

FROM:    self.config = ConfigParser.ConfigParser()
TO:    self.config = configparser.ConfigParser()

Change:
FROM            f = urllib.urlopen(self.url + "/json.htm?type=command&p..............
TO                  f = urllib.request.urlopen(self.url + "/json.htm?type=command&p...................
